name: contabilidavoz
description: Aplicación móvil de contabilidad por voz en Flutter
publish_to: "none" # evita publicar accidentalmente en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
# Dependencias recomendadas
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

                            # 👇 Esto NO va dentro de flutter:, va al mismo nivel
scripts:
     
  build_apk: flutter build apk --release
  build_appbundle: flutter build appbundle --release
  clean_get: flutter clean && flutter pub get

  flutter:
   uses-material-design: true
